version: '2.1'

services:

  registry:
    image: venzyk/smarttodo-registry
    build: registry
    ports:
      - 8761:8761

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /docker/vol/mybootservice/mongodb/data:/data/db

  todo:
    image: venzyk/smarttodo-todo
    build: todo
    depends_on:
      - registry
#    links:
      - mongodb

    ports:
      - 8099:8099

  login:
    image: venzyk/smarttodo-login
    build: login
    depends_on:
      - registry
#    links:
      - mongodb

    ports:
      - 8077:8077

  gateway:
    image: venzyk/smarttodo-gateway
    build: gateway
    depends_on:
      - registry
      - login
      - todo
    ports:
      - 8888:8888

